name: Setup platform dependencies, python and scons.
description: 'Setup the platform dependencies (linuxbsd, javascript), and install pip version of scons.'
inputs:
  python-version:
    description: 'The python version to use'
    required: true
    default: '3.x'
  python-arch:
    description: 'The python architecture'
    required: true
    default: 'x64'
  platform:
    description: 'The platform to setup for, when it needs extra dependencies (linuxbsd/emscripten)'
    default: ''
runs:
  using: "composite"
  steps:
    - name: Linux dependencies
      shell: bash
      run: |
        if [ "${{ inputs.platform }}" == "linuxbsd" ]; then
            # Azure repositories are not reliable, we need to prevent azure giving us packages.
            sudo rm -f /etc/apt/sources.list.d/*
            sudo cp -f misc/ci/sources.list /etc/apt/sources.list
            sudo apt-get update
            # The actual dependencies
            sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
                libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev \
                libdbus-1-dev libudev-dev libxi-dev libxrandr-dev yasm xvfb wget unzip
        fi

    # Upload cache on completion and check it out now
    - name: Load .scons_cache directory
      id: linux-editor-cache
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/.scons_cache/
        key: ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
        restore-keys: |
          ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          ${{github.job}}-${{env.GODOT_BASE_BRANCH}}-${{github.ref}}
          ${{github.job}}-${{env.GODOT_BASE_BRANCH}}

    # Use python 3.x release (works cross platform)
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: ${{ inputs.python-version }}
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: ${{ inputs.python-arch }}

    - name: Setup scons
      shell: bash
      run: |
        python -c "import sys; print(sys.version)"
        python -m pip install scons
        scons --version
