name: 'Build Godot'
description: 'Build Godot with the provided options'
inputs:
  target:
    description: 'The scons target (debug/release_debug/release)'
    required: true
    default: 'debug'
  tools:
    description: 'If tools are to be built'
    required: true
    default: true
  platform:
    description: 'The Godot platform to build.'
    required: false
  sconsflags:
    default: ''
runs:
  using: "composite"
  steps:
    - name: Scons Build
      shell: sh
      run: |
          scons p={{ inputs.platform }} target=${{ inputs.target }} tools=${{ inputs.tools }} ${{ inputs.sconsflags }}
