#include "multiplayer_spawner.h"

#include "core/io/marshalls.h"
#include "core/multiplayer/multiplayer_replicator.h"
#include "scene/main/window.h"
#include "scene/resources/packed_scene.h"

#if 0
SceneReplicator *SceneReplicator::singleton = nullptr;

void SceneReplicator::_spawn_send(int p_peer_id, ResourceUID::ID p_scene_id, Object *p_obj, bool p_spawn) {
	PackedByteArray packet;
	int ofs = 0;

	SpawnableNode *base = Object::cast_to<SpawnableNode>(p_obj);

	// Prepare simplified path
	const Node *node = base->get_node();
	ERR_FAIL_COND(!node);
	MultiplayerSpawner *spawner = Object::cast_to<MultiplayerSpawner>(base->get_spawner());
	ERR_FAIL_COND(node->get_parent() != spawner->get_parent());
	Ref<MultiplayerAPI> multiplayer = spawner->get_multiplayer();
	//PackedByteArray state = multiplayer->get_replicator()->encode_state(p_scene_id, node, true);
	PackedByteArray state; // FIXME

	const Node *root_node = multiplayer->get_root_node();
	ERR_FAIL_COND(!root_node);
	NodePath rel_path = (root_node->get_path()).rel_path_to(spawner->get_path());

	int path_id = 0;
	multiplayer->send_confirm_path(spawner, rel_path, p_peer_id, path_id);

	// Encode name and parent ID.
	CharString cname = node->get_name().operator String().utf8();
	int nlen = encode_cstring(cname.get_data(), nullptr);
	packet.resize(4 + 4 + nlen + state.size());
	uint8_t *ptr = packet.ptrw();
	ofs = 0;
	ofs += encode_uint32(path_id, &ptr[ofs]);
	ofs += encode_uint32(nlen, &ptr[ofs]);
	ofs += encode_cstring(cname.get_data(), &ptr[ofs]);
	if (state.size()) {
		memcpy(&ptr[ofs], state.ptr(), state.size());
	}
	// FIXME
	if (p_spawn) {
		//multiplayer->get_replicator()->send_spawn(p_peer_id, p_scene_id, packet);
	} else {
		//multiplayer->get_replicator()->send_despawn(p_peer_id, p_scene_id, packet);
	}
}

void SceneReplicator::_spawn_receive(int p_from, ResourceUID::ID p_scene_id, const Variant &p_data, bool p_spawn, Ref<MultiplayerAPI> p_multiplayer) {
	ERR_FAIL_COND_MSG(p_data.get_type() != Variant::PACKED_BYTE_ARRAY, "Invalid spawn packet received");
	PackedByteArray packet = p_data;
	const uint8_t *ptr = packet.ptr();
	ERR_FAIL_COND_MSG(packet.size() < 9, "Invalid spawn packet received");
	int ofs = 0;
	uint32_t node_target = decode_uint32(&ptr[ofs]);
	Ref<MultiplayerAPI> multiplayer = p_multiplayer;
	Node *parent = multiplayer->get_cached_node(p_from, node_target);
	MultiplayerSpawner *spawner = Object::cast_to<MultiplayerSpawner>(parent);
	ERR_FAIL_COND(!parent);
	parent = spawner->get_parent();
	ofs += 4;
	ERR_FAIL_COND_MSG(parent == nullptr, "Invalid packet received. Requested node was not found.");

	uint32_t name_len = decode_uint32(&ptr[ofs]);
	ofs += 4;
	ERR_FAIL_COND_MSG(name_len > uint32_t(packet.size() - ofs), vformat("Invalid spawn packet size: %d, wants: %d", packet.size(), ofs + name_len));
	ERR_FAIL_COND_MSG(name_len < 1, "Zero spawn name size.");

	// We need to make sure no trickery happens here (e.g. despawning a subpath), but we want to allow autogenerated ("@") node names.
	const String name = String::utf8((const char *)&ptr[ofs], name_len);
	ERR_FAIL_COND_MSG(name.validate_node_name() != name.replace("@", ""), vformat("Invalid node name received: '%s'", name));
	ofs += name_len;

	const PackedByteArray state = packet.subarray(ofs, packet.size() - 1);
	if (p_from == 1) {
		String scene_path = ResourceUID::get_singleton()->get_id_path(p_scene_id);
		if (p_spawn) {
			ERR_FAIL_COND_MSG(parent->has_node(name), vformat("Unable to spawn node. Node already exists: %s/%s", parent->get_path(), name));
			RES res = ResourceLoader::load(scene_path);
			ERR_FAIL_COND_MSG(!res.is_valid(), "Unable to load scene to spawn at path: " + scene_path);
			PackedScene *scene = Object::cast_to<PackedScene>(res.ptr());
			ERR_FAIL_COND(!scene);
			Node *node = scene->instantiate();
			ERR_FAIL_COND(!node);
			//replicated_nodes[node->get_instance_id()] = p_scene_id;
			//_track(p_scene_id, node);
			// FIXME
			//multiplayer->get_replicator()->decode_state(p_scene_id, node, state, true);
			parent->_add_child_nocheck(node, name);
			spawner->emit_signal(SNAME("spawned"), p_scene_id, node);
		} else {
			ERR_FAIL_COND_MSG(!parent->has_node(name), vformat("Path not found: %s/%s", parent->get_path(), name));
			Node *node = parent->get_node(name);
			//ERR_FAIL_COND_MSG(!replicated_nodes.has(node->get_instance_id()), vformat("Trying to despawn a Node that was not replicated: %s/%s", parent->get_path(), name));
			spawner->emit_signal(SNAME("despawned"), p_scene_id, node);
			//_untrack(p_scene_id, node);
			//replicated_nodes.erase(node->get_instance_id());
			node->queue_delete();
		}
	} else {
		if (p_spawn) {
			spawner->emit_signal(SNAME("spawn_requested"), p_from, p_scene_id, parent, name, state);
		} else {
			spawner->emit_signal(SNAME("despawn_requested"), p_from, p_scene_id, parent, name, state);
		}
	}
}

void SceneReplicator::add_spawnable(Ref<MultiplayerAPI> p_multiplayer, const ResourceUID::ID &p_id, const TypedArray<StringName> &p_initial_state) {
	Variant v = p_multiplayer;
	const Variant *argv = &v;
	// FIXME
	//p_multiplayer->get_replicator()->spawn_config(p_id, MultiplayerReplicator::REPLICATION_MODE_CUSTOM, p_initial_state, callable_mp(this, &SceneReplicator::_spawn_send), callable_mp(this, &SceneReplicator::_spawn_receive).bind(&argv, 1));
}
#endif

void MultiplayerSpawner::_bind_methods() {
	ClassDB::bind_method(D_METHOD("spawn", "node", "peer"), &MultiplayerSpawner::spawn, DEFVAL(0));
	ClassDB::bind_method(D_METHOD("get_spawnable_scenes"), &MultiplayerSpawner::get_spawnable_scenes);
	ClassDB::bind_method(D_METHOD("set_spawnable_scenes", "scenes"), &MultiplayerSpawner::set_spawnable_scenes);

	ADD_PROPERTY(PropertyInfo(Variant::ARRAY, "replication", PROPERTY_HINT_ARRAY_TYPE, vformat("%s/%s:%s", Variant::OBJECT, PROPERTY_HINT_RESOURCE_TYPE, "PackedScene"), (PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_SCRIPT_VARIABLE)), "set_spawnable_scenes", "get_spawnable_scenes");

	ADD_SIGNAL(MethodInfo("despawned", PropertyInfo(Variant::INT, "scene_id"), PropertyInfo(Variant::OBJECT, "node", PROPERTY_HINT_RESOURCE_TYPE, "Node")));
	ADD_SIGNAL(MethodInfo("spawned", PropertyInfo(Variant::INT, "scene_id"), PropertyInfo(Variant::OBJECT, "node", PROPERTY_HINT_RESOURCE_TYPE, "Node")));
}

void MultiplayerSpawner::_notification(int p_what) {
	if (p_what == NOTIFICATION_ENTER_TREE) {
		//get_multiplayer()->get_replicator()->register_spawner(get_path(), &_spawn_despawn_cb);
	} else if (p_what == NOTIFICATION_EXIT_TREE) {
		//get_multiplayer()->get_replicator()->deregister_spawner(get_path());
	}
}

TypedArray<PackedScene> MultiplayerSpawner::get_spawnable_scenes() const {
	TypedArray<PackedScene> out;
	for (const Ref<PackedScene> &scene : spawnable_scenes) {
		out.push_back(scene);
	}
	return out;
}

void MultiplayerSpawner::set_spawnable_scenes(const TypedArray<PackedScene> &p_scenes) {
	spawnable_scenes.clear();
	for (int i = 0; i < p_scenes.size(); i++) {
		spawnable_scenes.push_back(p_scenes[i]);
	}
}

Error MultiplayerSpawner::spawn(Node *p_node, int p_peer) {
	ERR_FAIL_COND_V(!is_inside_tree(), ERR_UNCONFIGURED);
	// TODO must be a scene, must be replicated!
	const String scene = p_node->get_scene_file_path();
	if (scene.is_empty()) {
		return ERR_INVALID_PARAMETER;
	}
	//ResourceUID::ID id = ResourceLoader::get_resource_uid(scene);
	//spawning->setup(p_node, this);
	//get_parent()->add_child(p_node);
	// FIXME
	//get_multiplayer()->get_replicator()->spawn(id, spawning.ptr(), 0);
	return OK;
}
