#include "scene_tree_replicator.h"

#include "core/io/marshalls.h"
#include "core/multiplayer/multiplayer_api.h"
#include "scene/main/node.h"
#include "scene/multiplayer/multiplayer_spawner.h"
#include "scene/multiplayer/multiplayer_synchronizer.h"

MultiplayerReplicationInterface *SceneTreeReplicatorInterface::_create() {
	return memnew(SceneTreeReplicatorInterface);
}

void SceneTreeReplicatorInterface::make_default() {
	MultiplayerAPI::create_default_replication_interface = _create;
}

Error SceneTreeReplicatorInterface::_send_spawn_despawn(const TrackedObject &p_tracked, int p_peer, bool p_spawn) {
	ERR_FAIL_COND_V(!multiplayer, ERR_BUG);
	Node *node = p_tracked.get_node();
	MultiplayerSpawner *spawner = p_tracked.get_spawner();
	ERR_FAIL_COND_V(!spawner, ERR_BUG);
	ERR_FAIL_COND_V(!node, ERR_BUG);
	const String scene_path = node->get_scene_file_path();
	ERR_FAIL_COND_V(scene_path.is_empty(), ERR_BUG);
	ResourceUID::ID scene_id = ResourceLoader::get_resource_uid(scene_path);
	ERR_FAIL_COND_V(scene_id == ResourceUID::INVALID_ID, ERR_BUG);

	PackedByteArray packet;

	// Prepare simplified path
	//PackedByteArray state = multiplayer->get_replicator()->encode_state(p_scene_id, node, true);
	PackedByteArray state; // FIXME

	const Node *root_node = multiplayer->get_root_node();
	ERR_FAIL_COND_V(!root_node, ERR_UNCONFIGURED);
	NodePath rel_path = (root_node->get_path()).rel_path_to(spawner->get_path());

	int path_id = 0;
	multiplayer->send_confirm_path(spawner, rel_path, p_peer, path_id);

	// Encode name and parent ID.
	CharString cname = node->get_name().operator String().utf8();
	int nlen = encode_cstring(cname.get_data(), nullptr);
	packet.resize(8 + 4 + 4 + 4 + nlen + state.size());
	int ofs = 0;
	uint8_t *ptr = packet.ptrw();
	ofs += encode_uint64(scene_id, &ptr[ofs]);
	ofs += encode_uint32(path_id, &ptr[ofs]);
	ofs += encode_uint32(p_tracked.net_id.get_id(), &ptr[ofs]);
	ofs += encode_uint32(nlen, &ptr[ofs]);
	ofs += encode_cstring(cname.get_data(), &ptr[ofs]);
	if (state.size()) {
		memcpy(&ptr[ofs], state.ptr(), state.size());
	}
	if (p_spawn) {
		return send_spawn(packet, p_peer);
	} else {
		return send_despawn(packet, p_peer);
	}
}

Error SceneTreeReplicatorInterface::_spawn_despawn_receive(int p_from, const uint8_t *p_buffer, int p_buffer_len, bool p_spawn) {
	ERR_FAIL_COND_V_MSG(p_buffer_len < 21, ERR_INVALID_DATA, "Invalid spawn packet received");
	int ofs = 1; // The spawn/despawn command.
	ResourceUID::ID scene_id = decode_uint64(&p_buffer[ofs]);
	ofs += 8;
	uint32_t node_target = decode_uint32(&p_buffer[ofs]);
	ofs += 4;
	uint32_t net_id = decode_uint32(&p_buffer[ofs]);
	ofs += 4;
	Node *parent = multiplayer->get_cached_node(p_from, node_target);
	MultiplayerSpawner *spawner = Object::cast_to<MultiplayerSpawner>(parent);
	ERR_FAIL_COND_V(!spawner, ERR_DOES_NOT_EXIST);

	uint32_t name_len = decode_uint32(&p_buffer[ofs]);
	ofs += 4;
	ERR_FAIL_COND_V_MSG(name_len > uint32_t(p_buffer_len - ofs), ERR_INVALID_DATA, vformat("Invalid spawn packet size: %d, wants: %d", p_buffer_len, ofs + name_len));
	ERR_FAIL_COND_V_MSG(name_len < 1, ERR_INVALID_DATA, "Zero spawn name size.");

	// We need to make sure no trickery happens here (e.g. despawning a subpath), but we want to allow autogenerated ("@") node names.
	const String name = String::utf8((const char *)&p_buffer[ofs], name_len);
	ERR_FAIL_COND_V_MSG(name.validate_node_name() != name.replace("@", ""), ERR_INVALID_DATA, vformat("Invalid node name received: '%s'", name));
	ofs += name_len;

	PackedByteArray state;
	int state_len = p_buffer_len - ofs;
	if (state_len) {
		state.resize(state_len);
		memcpy(state.ptrw(), p_buffer, state_len);
	}
	if (p_spawn) {
		ObjectID oid;
		Error err = spawner->remote_spawn(p_from, scene_id, name, state, oid);
		if (err == OK) {
			remote_objects[NetID(net_id, p_from)] = oid;
		}
		return err;
	} else {
		NetID nid(net_id, p_from);
		if (!remote_objects.has(nid)) {
			return ERR_INVALID_DATA;
		}
		// TODO, really, validate name!
		remote_objects.erase(nid);
		return spawner->remote_despawn(p_from, scene_id, name, state);
	}
}

Error SceneTreeReplicatorInterface::on_spawn_send(Object *p_obj, int p_peer) {
	if (p_obj->is_class_ptr(MultiplayerSpawner::get_class_ptr_static())) {
		MultiplayerSpawner *spawner = Object::cast_to<MultiplayerSpawner>(p_obj);
		ERR_FAIL_COND_V(!spawner, ERR_BUG);
		ERR_FAIL_COND_V(!spawner->get_currently_spawning(), ERR_INVALID_PARAMETER);
		Node *node = spawner->get_currently_spawning();
		ObjectID oid = node->get_instance_id();
		// TODO we should totally allow this in the future.
		ERR_FAIL_COND_V(tracked_objects.has(oid), ERR_INVALID_PARAMETER);
		TrackedObject tobj(oid, NetID(++last_net_id));
		tobj.spawner = spawner->get_instance_id();
		tracked_objects[oid] = tobj;
		Error err = spawner->local_spawn();
		ERR_FAIL_COND_V(err != OK, err);
		ERR_FAIL_COND_V(!tracked_objects.has(oid), ERR_BUG);
		TrackedObject &tracked = tracked_objects[oid];
		if (tracked.pending) {
			tracked.pending = false;
			return _send_spawn_despawn(tracked, p_peer, true);
		}
		return OK;
	} else if (p_obj->is_class_ptr(MultiplayerSynchronizer::get_class_ptr_static())) {
		MultiplayerSynchronizer *synchronizer = Object::cast_to<MultiplayerSynchronizer>(p_obj);
		ERR_FAIL_COND_V(!synchronizer, ERR_BUG);
		const NodePath path = synchronizer->get_root_path();
		ERR_FAIL_COND_V(path.is_empty() || !synchronizer->has_node(path), ERR_UNCONFIGURED);
		Node *node = synchronizer->get_node(path);
		ObjectID oid = node->get_instance_id();
		if (tracked_objects.has(oid)) {
			TrackedObject &tracked = tracked_objects[oid];
			tracked.synchronizer = synchronizer->get_instance_id();
			if (tracked.pending) {
				WARN_PRINT("You got this!");
				// TODO should send with initial state if possible.
				//tracked.pending = false;
				//return _send_spawn_despawn(spawner, spawner->get_currently_spawning(), p_peer, true);
			}
		}
		return OK;
	} else {
		return ERR_INVALID_PARAMETER;
	}
}

Error SceneTreeReplicatorInterface::on_spawn_receive(int p_from, const uint8_t *p_buffer, int p_buffer_len) {
	return _spawn_despawn_receive(p_from, p_buffer, p_buffer_len, true);
}

Error SceneTreeReplicatorInterface::on_despawn_send(Object *p_obj, int p_peer) {
	if (p_obj->is_class_ptr(MultiplayerSpawner::get_class_ptr_static())) {
		// TODO
		MultiplayerSpawner *spawner = Object::cast_to<MultiplayerSpawner>(p_obj);
		ERR_FAIL_COND_V(!spawner, ERR_INVALID_PARAMETER);
		return OK;
		//return _send_spawn_despawn(spawner, node, p_peer, false);
	} else if (p_obj->is_class_ptr(MultiplayerSynchronizer::get_class_ptr_static())) {
		// TODO
		//tracked.synchronizer = 0;
		return OK;
	} else {
		return ERR_INVALID_PARAMETER;
	}
}

Error SceneTreeReplicatorInterface::on_despawn_receive(int p_from, const uint8_t *p_buffer, int p_buffer_len) {
	return _spawn_despawn_receive(p_from, p_buffer, p_buffer_len, false);
}

Error SceneTreeReplicatorInterface::on_sync_send(Object *p_obj, int p_peer) {
	Node *node = Object::cast_to<Node>(p_obj);
	ERR_FAIL_COND_V(!node, ERR_INVALID_PARAMETER);
	return OK;
}

Error SceneTreeReplicatorInterface::on_sync_receive(int p_from, const uint8_t *p_buffer, int p_buffer_len) {
	return OK;
}

SceneTreeReplicatorInterface::SceneTreeReplicatorInterface() {
}

SceneTreeReplicator::SceneTreeReplicator() {
}

SceneTreeReplicator::~SceneTreeReplicator() {
}
