#include "multiplayer_spawner.h"

#include "core/io/marshalls.h"
#include "core/multiplayer/multiplayer_replicator.h"
#include "scene/main/window.h"
#include "scene/resources/packed_scene.h"

void MultiplayerSpawner::_bind_methods() {
	ClassDB::bind_method(D_METHOD("spawn", "node", "data"), &MultiplayerSpawner::spawn, DEFVAL(PackedByteArray()));

	ADD_SIGNAL(MethodInfo("despawned", PropertyInfo(Variant::INT, "scene_id"), PropertyInfo(Variant::OBJECT, "node", PROPERTY_HINT_RESOURCE_TYPE, "Node")));
	ADD_SIGNAL(MethodInfo("spawned", PropertyInfo(Variant::INT, "scene_id"), PropertyInfo(Variant::OBJECT, "node", PROPERTY_HINT_RESOURCE_TYPE, "Node")));
	ADD_SIGNAL(MethodInfo("despawn_requested", PropertyInfo(Variant::INT, "id"), PropertyInfo(Variant::INT, "scene_id"), PropertyInfo(Variant::OBJECT, "parent", PROPERTY_HINT_RESOURCE_TYPE, "Node"), PropertyInfo(Variant::STRING, "name"), PropertyInfo(Variant::PACKED_BYTE_ARRAY, "data")));
	ADD_SIGNAL(MethodInfo("spawn_requested", PropertyInfo(Variant::INT, "id"), PropertyInfo(Variant::INT, "scene_id"), PropertyInfo(Variant::OBJECT, "parent", PROPERTY_HINT_RESOURCE_TYPE, "Node"), PropertyInfo(Variant::STRING, "name"), PropertyInfo(Variant::PACKED_BYTE_ARRAY, "data")));
}

void MultiplayerSpawner::_spawn_despawn_cb(const NodePath &p_path, int p_from, const ResourceUID::ID &p_scene_id, const String &p_name, const PackedByteArray &p_data, bool p_spawn) {
	MultiplayerSpawner *node = Object::cast_to<MultiplayerSpawner>(SceneTree::get_singleton()->get_root()->get_node(p_path));
	ERR_FAIL_COND(!node);
	node->_spawn_despawn(p_from, p_scene_id, p_name, p_data, p_spawn);
}

void MultiplayerSpawner::_spawn_despawn(int p_from, const ResourceUID::ID &p_scene_id, const String &p_name, const PackedByteArray &p_data, bool p_spawn) {
	// We need to make sure no trickery happens here (e.g. despawning a subpath), but we want to allow autogenerated ("@") node names.
	ERR_FAIL_COND_MSG(p_name.validate_node_name() != p_name.replace("@", ""), vformat("Invalid node name received: '%s'", p_name));

	Node *parent = this; // TODO should be parent.
	if (p_from == 1) {
		String scene_path = ResourceUID::get_singleton()->get_id_path(p_scene_id);
		if (p_spawn) {
			ERR_FAIL_COND_MSG(parent->has_node(p_name), vformat("Unable to spawn node. Node already exists: %s/%s", parent->get_path(), p_name));
			RES res = ResourceLoader::load(scene_path);
			ERR_FAIL_COND_MSG(!res.is_valid(), "Unable to load scene to spawn at path: " + scene_path);
			PackedScene *scene = Object::cast_to<PackedScene>(res.ptr());
			ERR_FAIL_COND(!scene);
			Node *node = scene->instantiate();
			ERR_FAIL_COND(!node);
			//replicated_nodes[node->get_instance_id()] = p_scene_id;
			//_track(p_scene_id, node);
			get_multiplayer()->get_replicator()->decode_state(p_scene_id, node, p_data, true);
			parent->_add_child_nocheck(node, p_name);
			emit_signal(SNAME("spawned"), p_scene_id, node);
		} else {
			ERR_FAIL_COND_MSG(!parent->has_node(p_name), vformat("Path not found: %s/%s", parent->get_path(), p_name));
			Node *node = parent->get_node(p_name);
			//ERR_FAIL_COND_MSG(!replicated_nodes.has(node->get_instance_id()), vformat("Trying to despawn a Node that was not replicated: %s/%s", parent->get_path(), p_name));
			emit_signal(SNAME("despawned"), p_scene_id, node);
			//_untrack(p_scene_id, node);
			//replicated_nodes.erase(node->get_instance_id());
			node->queue_delete();
		}
	} else {
		if (p_spawn) {
			emit_signal(SNAME("spawn_requested"), p_from, p_scene_id, parent, p_name, p_data);
		} else {
			emit_signal(SNAME("despawn_requested"), p_from, p_scene_id, parent, p_name, p_data);
		}
	}
}

void MultiplayerSpawner::_notification(int p_what) {
	if (p_what == NOTIFICATION_ENTER_TREE) {
		get_multiplayer()->get_replicator()->register_spawner(get_path(), &_spawn_despawn_cb);
	} else if (p_what == NOTIFICATION_EXIT_TREE) {
		get_multiplayer()->get_replicator()->deregister_spawner(get_path());
	}
}

Error MultiplayerSpawner::spawn(Node *p_node, const PackedByteArray &p_data) {
	ERR_FAIL_COND_V(!is_inside_tree(), ERR_UNCONFIGURED);
	// TODO must be a scene, must be replicated!
	const String scene = p_node->get_scene_file_path();
	if (scene.is_empty()) {
		return ERR_INVALID_PARAMETER;
	}
	ResourceUID::ID id = ResourceLoader::get_resource_uid(scene);
	add_child(p_node); // TODO should be parent
	get_multiplayer()->get_replicator()->spawn(id, p_node, 0);
	return OK;
}

MultiplayerSpawner::MultiplayerSpawner() {
}
