#!/usr/bin/env python

Import("env")
Import("env_modules")

env_webrtc = env_modules.Clone()

# Extension is retained in Javascript for export compatibility
env_webrtc.Append(CPPDEFINES=["WEBRTC_EXTENSION_ENABLED"])

if env["platform"] == "javascript":
    # Our JavaScript/C++ interface.
    env.AddJSLibraries(["library_godot_webrtc.js"])

env_webrtc.add_source_files(env.modules_sources, "*.cpp")
