name: 🍎 macOS Builds
on: [push, pull_request]

# Global Settings
env:
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes debug_symbols=no module_text_server_fb_enabled=yes
  SCONS_CACHE_LIMIT: 4096

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: true

jobs:
  build-windows:
    runs-on: "macos-latest"
    name: 🍎 macOS Builds
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macos-editor
            target: release_debug
            tools: true
            tests: true
            SCONSFLAGS: ""
            bin: "./bin/godot.osx.opt.tools.64"

          - name: macos-template
            target: release
            tools: false
            tests: false
            SCONSFLAGS: ""

    steps:
      - uses: actions/checkout@v2

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot_deps

      - name: Compilation
        uses: ./.github/actions/godot_build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.SCONSFLAGS }}
          platform: osx
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}
          tests: ${{ matrix.tests }}

      # Execute unit tests for the editor
      - name: Unit Tests
        if: ${{ matrix.tests }}
        run: |
          ${{ matrix.bin }} --test

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.name }}
