name: 🏁 Windows Builds
on: [push, pull_request]

# Global Settings
# SCONS_CACHE for windows must be set in the build environment
env:
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=all werror=yes debug_symbols=no module_text_server_fb_enabled=yes
  SCONS_CACHE_MSVC_CONFIG: true
  SCONS_CACHE_LIMIT: 3072

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: true

jobs:
  build-windows:
    # Windows 10 with latest image
    runs-on: "windows-latest"
    name: 🏁 Windows Builds
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: windows-editor
            target: release_debug
            tools: true
            tests: true
            SCONSFLAGS: ""
            bin: "./bin/godot.windows.opt.tools.64.exe"

          - name: window-template
            target: release
            tools: false
            tests: false
            SCONSFLAGS: ""

    steps:
      - uses: actions/checkout@v2

      - name: Setup python and scons
        uses: ./.github/actions/godot_deps
        with:
          cache-name: ${{ matrix.name }}

      - name: Compilation
        uses: ./.github/actions/godot_build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.SCONSFLAGS }}
          platform: windows
          target: ${{ matrix.target }}
          tools: ${{ matrix.tools }}
          tests: ${{ matrix.tests }}

      # Execute unit tests for the editor
      - name: Unit Tests
        if: ${{ matrix.tests }}
        run: |
          ${{ matrix.bin }} --test

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.name }}
